version: '3.9'

volumes:
    app_data:


services:
    ui:
        container_name: emse_ui_lib
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        tty: true
        expose:
            - '6006'
        ports:
            - '6006:6006'
        volumes:
            -   app_data:/usr/src/app/src
            -   ./.storybook:/usr/src/app/.storybook
        networks:
            - ui_network
        command: yarn storybook
    prettier:
        container_name: emse_ui_lib_prettier
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - app_data:/usr/src/app/src
        networks:
            - ui_network
        command: npx onchange "**/*" -- npx prettier --write --config ./.prettierrc --ignore-unknown {{changed}}
    tailwind:
        container_name: emse_ui_lib_tailwind
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - app_data:/usr/src/app/src
        networks:
            - ui_network
        command: yarn style
networks:
    ui_network: